#!/usr/bin/env bash
# Stage the dev-HA verification environment.
#
# Assembles deploy/homeassistant/dev-config/ as a standalone HA config dir:
#   - dev-configuration.yaml  -> configuration.yaml  (fragment + default_config:)
#   - homeassistant/packages/ -> packages/           (the files under test, verbatim)
#   - homeassistant/themes/   -> themes/
#   - built card modules      -> www/
#   - generated secrets.yaml pointed at the Grocy container
#
# Idempotent — safe to re-run after a rebuild. Re-running preserves the HA
# database and login in dev-config/, so you only onboard once.
#
# Requires GROCY_API_KEY in the environment. Read it out of the running Grocy with:
#   sqlite3 deploy/grocy/grocy-config/data/grocy.db "select api_key from api_keys limit 1;"
#
# The key is written only into dev-config/secrets.yaml (gitignored). It never
# reaches the browser: HA holds it and the card calls the rest_command by name.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/deploy/homeassistant"
CARD_DIR="$REPO_ROOT/custom_cards/grocy-food-card"
DEV_CONFIG="$DEPLOY_DIR/dev-config"

if [[ -z "${GROCY_API_KEY:-}" ]]; then
  echo "ERROR: GROCY_API_KEY is not set. Read it from the Grocy SQLite db:" >&2
  echo '  sqlite3 deploy/grocy/grocy-config/data/grocy.db "select api_key from api_keys limit 1;"' >&2
  exit 1
fi

# Grocy is reached at the HOST's published port from inside the HA container.
GROCY_HOST="${GROCY_HOST:-host.docker.internal:9283}"

echo "==> Building the card"
cd "$CARD_DIR"
npm run build

echo "==> Assembling $DEV_CONFIG"
mkdir -p "$DEV_CONFIG/www"
cp "$DEPLOY_DIR/dev-configuration.yaml" "$DEV_CONFIG/configuration.yaml"

# The packages are the artifact under test — copy them verbatim, replacing any
# earlier copy so a stale grocy_recipes.yaml can never survive a re-run.
rm -rf "$DEV_CONFIG/packages" "$DEV_CONFIG/themes"
cp -R "$REPO_ROOT/homeassistant/packages" "$DEV_CONFIG/packages"
cp -R "$REPO_ROOT/homeassistant/themes"   "$DEV_CONFIG/themes"

# Packages that reference secrets we don't provide would abort HA startup. Only
# the Grocy package is under test here; drop the rest from the dev config.
find "$DEV_CONFIG/packages" -type f ! -name 'grocy_recipes.yaml' -delete
find "$DEV_CONFIG/packages" -type f -name '.calendar-verify.py' -delete 2>/dev/null || true

echo "==> Copying card modules into www/"
# Each card is a SELF-CONTAINED bundle (vite inlines lit + shared.ts), so there
# is no shared.js to copy — see vite.config.ts. A bare `tsc` build emitted
# `import ... from "lit"`, which no browser can resolve; HA reported only
# "Configuration error" and the card never loaded.
cp "$CARD_DIR/dist/recipe-card.js" \
   "$CARD_DIR/dist/mealplan-card.js" \
   "$CARD_DIR/dist/shopping-card.js" \
   "$DEV_CONFIG/www/"

echo "==> Writing secrets.yaml"
# NOTE the URL encoding: Grocy's filter syntax is query[]=recipe_id=N, and an
# unencoded '[' does not survive HA's URL handling (INSTALL.md:101). The
# {{ recipe_id }} placeholder is templated by HA from the card's service-call
# data — proving that substitution happens is the point of this exercise.
cat > "$DEV_CONFIG/secrets.yaml" <<EOF
# Generated by deploy/homeassistant/dev-setup.sh — DEV ONLY, never committed.
grocy_api_key: "$GROCY_API_KEY"
grocy_recipes_url: "http://$GROCY_HOST/api/objects/recipes"
grocy_recipe_ingredients_url: >-
  http://$GROCY_HOST/api/objects/recipes_pos_resolved?query%5B%5D=recipe_id%3D{{ recipe_id }}
grocy_quantity_units_url: "http://$GROCY_HOST/api/objects/quantity_units"
EOF

echo
echo "Staged. Next:"
echo "  docker compose -f deploy/homeassistant/docker-compose.ha-dev.yml up -d"
echo "  open http://localhost:8124   # first run: create an account, then add the resource"
echo
echo "⚠️  If the card was ALREADY registered as a resource, bump its version:"
echo "      Settings -> Dashboards -> Resources -> /local/recipe-card.js?v=<n+1>"
echo "    Browsers cache Lovelace modules through a hard refresh; changing the URL is"
echo "    what forces a re-fetch. A stale module shows as 'Configuration error' even"
echo "    though the file on disk is correct. HA logs the browser's real error under"
echo "    frontend.js.modern in /config/home-assistant.log."
